In [1]:
from pathlib import Path

RAW = Path("../data/raw")
for p in sorted(RAW.rglob("*")):
    if p.is_file():
        print(f"{p.stat().st_size / 1e6:9.2f} MB  {p.relative_to(RAW)}")

     0.00 MB  .gitkeep
     7.39 MB  5EnvSensor_MayToDec2024_180kRows.zip
    84.86 MB  5occupancySensor_MayToDec2024_9MRows.zip
   122.77 MB  Example Data (Do not use)\Detailed_14_07_26 - 17_07_26.csv
     0.23 MB  Example Data (Do not use)\Env_data_MSI_Lab - 30-07-2025_19-12-2025.csv
     1.06 MB  Example Data (Do not use)\Map_XY.png
   216.21 MB  Example Data (Do not use)\PMV_07_25 - 04_26.csv
     0.02 MB  Sensor ID and Locations.xlsx

In [11]:
import pandas as pd

locations = pd.read_excel("../data/raw/Sensor ID and Locations.xlsx", dtype={"ID": str})
print(locations.shape)
locations.head(10)

(78, 6)

   Building Floor/Room              Area Physical Label Sensor             ID
0        60     1-PS01          Corridor         ES1104    Env  6012003000486
1        69     1-PS02          Breakout         ES2113    Env  6012003000882
2        60       1.40        Board Room         ES1102    Env  6012003000462
3        60       1.41       Open Office         ES1110    Env  6012003000424
4        60      1.41A      Focus Room 1         ES1101    Env  6012003000448
5        60       1.42  Startup Workshop         ES1103    Env  6012003000479
6        60       1.43           Startup         ES1105    Env  6012003000493
7        60       1.45      Meeting Room         ES1106    Env  6012003000509
8        60       1.47          Corridor         ES1107    Env  6012003000516
9        60       1.49          Workshop         ES1108    Env  6012003000530

In [12]:
import pandas as pd

df = pd.read_excel("../data/raw/Sensor ID and Locations.xlsx")

In [13]:
df.head()

   Building Floor/Room          Area Physical Label Sensor             ID
0        60     1-PS01      Corridor         ES1104    Env  6012003000486
1        69     1-PS02      Breakout         ES2113    Env  6012003000882
2        60       1.40    Board Room         ES1102    Env  6012003000462
3        60       1.41   Open Office         ES1110    Env  6012003000424
4        60      1.41A  Focus Room 1         ES1101    Env  6012003000448

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Building        78 non-null     int64
 1   Floor/Room      78 non-null     str
 2   Area            78 non-null     str
 3   Physical Label  78 non-null     str
 4   Sensor          78 non-null     str
 5   ID              78 non-null     int64
dtypes: int64(2), str(4)
memory usage: 3.8 KB

In [15]:
df.isna().sum()

Building          0
Floor/Room        0
Area              0
Physical Label    0
Sensor            0
ID                0
dtype: int64

In [16]:
locations["Sensor"].value_counts()

Sensor
Env    78
Name: count, dtype: int64

In [17]:
locations["Building"].value_counts()

Building
60    47
69    31
Name: count, dtype: int64

In [18]:
locations["Area"].value_counts()

Area
Lab                    8
Workshop               7
Corridor               4
Startup                4
Meeting Room           3
Motorsport             2
Motorsport_upper       2
Compactus_upper        2
Collaboration Area     2
Breakout               1
Board Room             1
Open Office            1
Focus Room 1           1
Startup Workshop       1
Collab Breakout (W)    1
Collab Breakout (E)    1
Open Office (West)     1
Open Office (East)     1
Electrical             1
Corridor (North)       1
Corridor (Comms)       1
Corridor (South)       1
West Entrance          1
Informal Breakout 1    1
Informal Breakout 2    1
Informal Breakout 3    1
Collab Space (West)    1
Collab Space (East)    1
MSM_3D Printers        1
MSM_Demo               1
MSM_CNC                1
MSM_Robot Charging     1
MSM_Central            1
MSM_Control Room       1
Precious Plastic       1
Fabrication 1          1
Fabrication 2          1
Sanding                1
Machining              1
Machining_upper        1
Composites 1_upper     1
Composites 2_upper     1
UAS                    1
UAS_upper              1
HPR                    1
Compactus              1
Kitchenette            1
NOVA                   1
NOVA_upper             1
Gallery Display        1
Living Lab 1           1
Living Lab 2           1
East Entrance          1
Name: count, dtype: int64

In [19]:
locations["ID"].is_unique

False

In [20]:
dups = locations[locations["ID"].duplicated(keep=False)].sort_values("ID")
print(len(dups), "rows share an ID")
dups

2 rows share an ID

    Building Floor/Room           Area Physical Label Sensor             ID
65        69       G.52       Workshop         ES2G14    Env  6012003000691
75        69       G.61  East Entrance         ES2G01    Env  6012003000691

In [21]:
locations["Physical Label"].is_unique

True

In [23]:
import zipfile
from pathlib import Path

# Find every zip in raw and show sizes, so you can tell the large one from the empty one
for z in Path("../data/raw").rglob("*.zip"):
    print(f"{z.stat().st_size / 1e6:9.1f} MB  {z}")

      7.4 MB  ..\data\raw\5EnvSensor_MayToDec2024_180kRows.zip
     84.9 MB  ..\data\raw\5occupancySensor_MayToDec2024_9MRows.zip

In [25]:
zip_path = Path("../data/raw/5occupancySensor_MayToDec2024_9MRows.zip")

with zipfile.ZipFile(zip_path) as z:
    infos = z.infolist()
    print(len(infos), "entries")
    print(f"{sum(i.file_size for i in infos) / 1e9:.2f} GB uncompressed")
    for i in infos[:25]:
        print(f"{i.file_size / 1e6:9.2f} MB  {i.filename}")

1 entries
1.61 GB uncompressed
  1605.04 MB  5occupancySensor_MayToDec2024_9MRows.csv

In [26]:
import pandas as pd

csv_name = "5occupancySensor_MayToDec2024_9MRows.csv"
with zipfile.ZipFile(zip_path) as z:
    with z.open(csv_name) as f:
        sample = pd.read_csv(f, nrows=1000)

sample.info()
sample.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         1000 non-null   int64
 1   deviceid                   1000 non-null   str
 2   floorspaceid               1000 non-null   str
 3   occupancystatus            1000 non-null   str
 4   headcount                  1000 non-null   int64
 5   collecteddate              1000 non-null   str
 6   occupancystatuschangedate  1000 non-null   str
 7   previousoccupancystatus    1000 non-null   str
dtypes: int64(2), str(6)
memory usage: 62.6 KB

,id,deviceid,floorspaceid,occupancystatus,headcount,collecteddate,occupancystatuschangedate,previousoccupancystatus
0,136043,56923747-b390-4f2a-8930-808429132266,941f0352-bb69-47d0-a9c5-ac29eb4f7319,CurrentlyOccupied,1,2023-11-24 00:36:52+11,2023-11-24 00:36:52+11,NotOccupied
1,136048,56923747-b390-4f2a-8930-808429132266,941f0352-bb69-47d0-a9c5-ac29eb4f7319,RecentlyOccupied,0,2023-11-24 00:37:32+11,2023-11-24 00:37:32+11,CurrentlyOccupied
2,136050,56923747-b390-4f2a-8930-808429132266,0f3f37f8-0335-41e0-ae87-a1d677dfc7d7,CurrentlyOccupied,1,2023-11-24 00:37:32+11,2023-11-24 00:37:32+11,NotOccupied
3,136052,56923747-b390-4f2a-8930-808429132266,941f0352-bb69-47d0-a9c5-ac29eb4f7319,NotOccupied,0,2023-11-24 00:37:52+11,2023-11-24 00:37:52+11,RecentlyOccupied
4,136053,56923747-b390-4f2a-8930-808429132266,0f3f37f8-0335-41e0-ae87-a1d677dfc7d7,RecentlyOccupied,0,2023-11-24 00:37:52+11,2023-11-24 00:37:52+11,CurrentlyOccupied
5,136058,56923747-b390-4f2a-8930-808429132266,0f3f37f8-0335-41e0-ae87-a1d677dfc7d7,NotOccupied,0,2023-11-24 00:38:32+11,2023-11-24 00:38:32+11,RecentlyOccupied
6,136067,56923747-b390-4f2a-8930-808429132266,941f0352-bb69-47d0-a9c5-ac29eb4f7319,CurrentlyOccupied,1,2023-11-24 00:40:52+11,2023-11-24 00:40:52+11,NotOccupied
7,136072,56923747-b390-4f2a-8930-808429132266,941f0352-bb69-47d0-a9c5-ac29eb4f7319,RecentlyOccupied,0,2023-11-24 00:41:32+11,2023-11-24 00:41:32+11,CurrentlyOccupied
8,136075,56923747-b390-4f2a-8930-808429132266,0f3f37f8-0335-41e0-ae87-a1d677dfc7d7,CurrentlyOccupied,1,2023-11-24 00:41:32+11,2023-11-24 00:41:32+11,NotOccupied
9,136079,56923747-b390-4f2a-8930-808429132266,941f0352-bb69-47d0-a9c5-ac29eb4f7319,NotOccupied,0,2023-11-24 00:41:52+11,2023-11-24 00:41:52+11,RecentlyOccupied

In [27]:
from pathlib import Path

for z in sorted(Path("../data/raw").rglob("*.zip")):
    print(f"{z.stat().st_size / 1e6:9.1f} MB  {z}")

      7.4 MB  ..\data\raw\5EnvSensor_MayToDec2024_180kRows.zip
     84.9 MB  ..\data\raw\5occupancySensor_MayToDec2024_9MRows.zip

In [28]:
import zipfile

zip2 = Path("../data/raw/5EnvSensor_MayToDec2024_180kRows.zip")

with zipfile.ZipFile(zip2) as z:
    infos = z.infolist()
    print(len(infos), "entries")
    print(f"{sum(i.file_size for i in infos) / 1e9:.2f} GB uncompressed")
    for i in infos[:30]:
        print(f"{i.file_size / 1e6:9.2f} MB  {i.filename}")

1 entries
0.35 GB uncompressed
   352.88 MB  5EnvSensor_MayToDec2024_180kRows.csv

In [30]:
import pandas as pd
import zipfile

zip2 = Path("../data/raw/5EnvSensor_MayToDec2024_180kRows.zip")   # same path you used for the listing
csv2 = "5EnvSensor_MayToDec2024_180kRows.csv"

with zipfile.ZipFile(zip2) as z:
    with z.open(csv2) as f:
        env_sample = pd.read_csv(f, nrows=1000)

print(env_sample.shape)
print(env_sample.columns.tolist())
env_sample.head(5)

(1000, 8)
['id', 'sensorid', 'devicetype', 'jsondata', 'status', 'processing_errors', 'createdate', 'processdate']

,id,sensorid,devicetype,jsondata,status,processing_errors,createdate,processdate
0,2,6012002000241,env,"[{""values"": [{""time"": 1702273965, ""value"": 4.1...",Processed,NaN,2024-02-29 03:11:58.210358+11,2024-02-29 03:11:58.210358+11
1,4,6012002000241,env,"[{""values"": [{""time"": 1702273965, ""value"": 4.1...",Processed,NaN,2024-02-29 17:09:08.833822+11,2024-02-29 17:09:08.833822+11
2,5,6012002000326,env,"[{""values"": [{""time"": 1702270857, ""value"": 4.1...",Processed,NaN,2024-02-29 17:09:12.444245+11,2024-02-29 17:09:12.444245+11
3,16,6012002000777,env,"[{""values"": [{""time"": 1683326565, ""value"": 4.1...",Processed,NaN,2024-02-29 17:10:24.443407+11,2024-02-29 17:10:24.443407+11
4,24,6012002000869,env,"[{""values"": [{""time"": 1709186696, ""value"": 4.1...",Processed,NaN,2024-02-29 17:11:11.348578+11,2024-02-29 17:11:11.348578+11

In [31]:
import json

print(env_sample.loc[0, "jsondata"][:1500])

parsed = json.loads(env_sample.loc[0, "jsondata"])
print(type(parsed), len(parsed))
print(parsed[0].keys())

[{"values": [{"time": 1702273965, "value": 4.1875}], "variable": {"id": 66, "name": "Battery", "unit": "V", "source": 0, "structure": 32834}}, {"values": [{"time": 1702273965, "value": 603}], "variable": {"id": 67, "name": "Carbon dioxide", "unit": "ppm", "source": 0, "structure": 32835}}, {"values": [{"time": 1702273965, "value": 66}], "variable": {"id": 72, "name": "Humidity", "unit": "HR%", "source": 0, "structure": 32840}}, {"values": [{"time": 1702273965, "value": 6}], "variable": {"id": 70, "name": "Formaldehyde", "unit": "µg/m3", "source": 0, "structure": 32847}}, {"values": [{"time": 1702273965, "value": 1011}], "variable": {"id": 80, "name": "Pressure", "unit": "mb", "source": 0, "structure": 32848}}, {"values": [{"time": 1702273965, "value": 23.8}], "variable": {"id": 84, "name": "Temperature", "unit": "°C", "source": 0, "structure": 32852}}, {"values": [{"time": 1702273965, "value": 14}], "variable": {"id": 99, "name": "Light Volatile Organic Compounds", "unit": "ppb", "source": 0, "structure": 32867}}, {"values": [{"time": 1702273965, "value": 8}], "variable": {"id": 47, "name": "Particulate matter 1", "unit": "µg/m3", "source": 1, "structure": 33071}}, {"values": [{"time": 1702273965, "value": 9}], "variable": {"id": 48, "name": "Particulate matter 4", "unit": "µg/m3", "source": 1, "structure": 33072}}, {"values": [{"time": 1702273965, "value": 9}], "variable": {"id": 49, "name": "Particulate matter 2.5", "unit": "µg/m3", "source": 1, "structure": 33073}}, {"valu
<class 'list'> 11
dict_keys(['values', 'variable'])

In [36]:
%%time
import zipfile
from pathlib import Path
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
from occupancy.loading import flatten_env_chunk

zip2 = Path("../data/raw/5EnvSensor_MayToDec2024_180kRows.zip")
csv2 = "5EnvSensor_MayToDec2024_180kRows.csv"
out_path = "../data/processed/env_long.parquet"
writer = None

with zipfile.ZipFile(zip2) as z, z.open(csv2) as f:
    for chunk in pd.read_csv(f, chunksize=20_000, usecols=["sensorid", "jsondata"]):
        flat = flatten_env_chunk(chunk)
        table = pa.Table.from_pandas(flat, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_path, table.schema)
        writer.write_table(table)
writer.close()

C:\Users\Elitebook\3001-OCCUPANCY-PROJECT\src\occupancy\loading.py:36: UserWarning: Skipped 13933 rows with missing or invalid jsondata
  warnings.warn(f"Skipped {n_bad} rows with missing or invalid jsondata")
C:\Users\Elitebook\3001-OCCUPANCY-PROJECT\src\occupancy\loading.py:36: UserWarning: Skipped 20000 rows with missing or invalid jsondata
  warnings.warn(f"Skipped {n_bad} rows with missing or invalid jsondata")
C:\Users\Elitebook\3001-OCCUPANCY-PROJECT\src\occupancy\loading.py:36: UserWarning: Skipped 20000 rows with missing or invalid jsondata
  warnings.warn(f"Skipped {n_bad} rows with missing or invalid jsondata")
C:\Users\Elitebook\3001-OCCUPANCY-PROJECT\src\occupancy\loading.py:36: UserWarning: Skipped 20000 rows with missing or invalid jsondata
  warnings.warn(f"Skipped {n_bad} rows with missing or invalid jsondata")
C:\Users\Elitebook\3001-OCCUPANCY-PROJECT\src\occupancy\loading.py:36: UserWarning: Skipped 20000 rows with missing or invalid jsondata
  warnings.warn(f"Skipped {n_bad} rows with missing or invalid jsondata")

CPU times: total: 19 s
Wall time: 19.1 s

C:\Users\Elitebook\3001-OCCUPANCY-PROJECT\src\occupancy\loading.py:36: UserWarning: Skipped 19447 rows with missing or invalid jsondata
  warnings.warn(f"Skipped {n_bad} rows with missing or invalid jsondata")

In [37]:
import json
from collections import Counter

zip2 = next(Path("../data/raw").rglob("5EnvSensor_MayToDec2024_180kRows.zip"))
csv2 = "5EnvSensor_MayToDec2024_180kRows.csv"

# read a later chunk (the 3rd block of 20,000 rows) with all columns
with zipfile.ZipFile(zip2) as z, z.open(csv2) as f:
    reader = pd.read_csv(f, chunksize=20_000)
    for i, chunk in enumerate(reader):
        if i == 2:
            break

print(chunk["devicetype"].value_counts(dropna=False))
print(chunk["status"].value_counts(dropna=False))
print(chunk["processing_errors"].notna().sum(), "rows with processing_errors")
print(chunk["jsondata"].isna().sum(), "rows with missing jsondata")

errors = Counter()
examples = {}
for raw in chunk["jsondata"]:
    try:
        payload = json.loads(raw)
        for var in payload:
            var["variable"]["name"]
            var["variable"]["unit"]
            for v in var["values"]:
                v["time"], v["value"]
    except Exception as e:
        key = type(e).__name__
        errors[key] += 1
        examples.setdefault(key, raw)

print(errors)
for k, v in examples.items():
    print("\n", k, ":", str(v)[:600])

devicetype
env    20000
Name: count, dtype: int64
status
Processed    20000
Name: count, dtype: int64
0 rows with processing_errors
0 rows with missing jsondata
Counter()

In [38]:
import json
from collections import Counter

with zipfile.ZipFile(zip2) as z, z.open(csv2) as f:
    for i, chunk in enumerate(pd.read_csv(f, chunksize=20_000)):
        errs, ex = Counter(), {}
        for raw in chunk["jsondata"]:
            try:
                payload = json.loads(raw)
                for var in payload:
                    var["variable"]["name"]; var["variable"]["unit"]
                    for v in var["values"]:
                        v["time"]; v["value"]
            except Exception as e:
                k = type(e).__name__
                errs[k] += 1
                ex.setdefault(k, str(raw)[:300])
        print(i, len(chunk), "missing:", chunk["jsondata"].isna().sum(), dict(errs))
        for k, s in ex.items():
            print("    ", k, "->", s)

0 20000 missing: 0 {}
1 20000 missing: 0 {}
2 20000 missing: 0 {}
3 20000 missing: 0 {'KeyError': 13933}
     KeyError -> [{"values": [{"time": 1702271273, "value": 4.1875}], "variable": {"id": 66, "name": "Battery", "unit": "V", "source": 0, "structure": 32834}}, {"values": [{"time": 1702271273, "value": 666}], "variable": {"id": 67, "name": "Carbon dioxide", "unit": "ppm", "source": 0, "structure": 32835}}, {"values"
4 20000 missing: 0 {'KeyError': 20000}
     KeyError -> [{"values": [{"time": 1702273965, "value": 4.1875}], "variable": {"id": 66, "name": "Battery", "unit": "V", "source": 0, "structure": 32834}}, {"values": [{"time": 1702273965, "value": 603}], "variable": {"id": 67, "name": "Carbon dioxide", "unit": "ppm", "source": 0, "structure": 32835}}, {"values"
5 20000 missing: 0 {'KeyError': 20000}
     KeyError -> [{"values": [{"time": 1702270857, "value": 4.1875}], "variable": {"id": 66, "name": "Battery", "unit": "V", "source": 0, "structure": 32834}}, {"values": [{"time": 1702270857, "value": 525}], "variable": {"id": 67, "name": "Carbon dioxide", "unit": "ppm", "source": 0, "structure": 32835}}, {"values"
6 20000 missing: 0 {'KeyError': 20000}
     KeyError -> [{"values": [{"time": 1702270857, "value": 4.1875}], "variable": {"id": 66, "name": "Battery", "unit": "V", "source": 0, "structure": 32834}}, {"values": [{"time": 1702270857, "value": 525}], "variable": {"id": 67, "name": "Carbon dioxide", "unit": "ppm", "source": 0, "structure": 32835}}, {"values"
7 20000 missing: 0 {'KeyError': 20000}
     KeyError -> [{"values": [{"time": 1747660084, "value": 4.1875}], "variable": {"id": 66, "name": "Battery", "unit": "V", "source": 0, "structure": 32834}}, {"values": [{"time": 1747660084, "value": 447}], "variable": {"id": 67, "name": "Carbon dioxide", "unit": "ppm", "source": 0, "structure": 32835}}, {"values"
8 19447 missing: 0 {'KeyError': 19447}
     KeyError -> [{"values": [{"time": 1770256299, "value": 4.1875}], "variable": {"id": 66, "name": "Battery", "unit": "V", "source": 0, "structure": 32834}}, {"values": [{"time": 1770256299, "value": 438}], "variable": {"id": 67, "name": "Carbon dioxide", "unit": "ppm", "source": 0, "structure": 32835}}, {"values"

In [39]:
from collections import Counter
import json

with zipfile.ZipFile(zip2) as z, z.open(csv2) as f:
    for i, chunk in enumerate(pd.read_csv(f, chunksize=20_000)):
        if i == 4:
            break

def find_problems(payload):
    out = []
    for var in payload:
        if "variable" not in var:
            out.append(("no 'variable' key", str(var)[:200])); continue
        for k in ("name", "unit"):
            if k not in var["variable"]:
                out.append((f"variable missing '{k}'", str(var["variable"])))
        if "values" not in var:
            out.append(("no 'values' key", str(var["variable"]))); continue
        for v in var["values"]:
            for k in ("time", "value"):
                if k not in v:
                    out.append((f"reading missing '{k}'", str(var["variable"].get("name"))))
    return out

counts, examples = Counter(), {}
for raw in chunk["jsondata"].head(2000):
    for label, detail in find_problems(json.loads(raw)):
        counts[label] += 1
        examples.setdefault(label, detail)

print(counts)
for k, v in examples.items():
    print(k, "->", v)

# also list the variable names present in a failing row
print([v["variable"].get("name") for v in json.loads(chunk["jsondata"].iloc[0])])

Counter({"reading missing 'value'": 2000})
reading missing 'value' -> Formaldehyde
['Battery', 'Carbon dioxide', 'Humidity', 'Formaldehyde', 'Pressure', 'Temperature', 'Light Volatile Organic Compounds', 'Particulate matter 1', 'Particulate matter 4', 'Particulate matter 2.5', 'Particulate matter 10']

In [40]:
row = json.loads(chunk["jsondata"].iloc[0])
print([v for v in row if v["variable"]["name"] == "Formaldehyde"])

[{'values': [{'time': 1702273965}], 'variable': {'id': 70, 'name': 'Formaldehyde', 'unit': 'µg/m3', 'source': 0, 'structure': 32847}}]